
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-07-23T20:43:34+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "ffdb8424a73f8681447d85cf8e91cb60a6d14681",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
